baseURL = 'https://www.andylee.tw/'
languageCode = 'zh-tw'
timeZone = "Asia/Taipei"
title = "Yu-Hsun Lee"
[permalinks]
post = "/slides/:slug/"
page = "/:slug/"
[params]
mainSections = ["post"]
[params.article]
readingTime = false
showDate = true
[markup.goldmark.renderer]
unsafe = true
[params.sidebar]
[menu]
[[menu.social]]
    name = "Github"
    url = "https://github.com/andylee830914"
    identifier = "Github"
    [menu.social.params]
        icon = "brand-github"
[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/andylee830914"
    identifier = "Twitter"
    [menu.social.params]
        icon = "brand-twitter"
[[menu.social]]
    name = "Email"
    url = "mailto:andylee0914.tw@gmail.com"
    identifier = "Email"
    [menu.social.params]
        icon = "messages"

[module]
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"